<script>
    import PanelLengua from "./Panel-lengua.svelte";


</script>

<div class="container">
    <h1>¿MONTAJE?</h1>
    <p>Un programa de televisión denominado <a href='https://youtu.be/KXthGnsMY0w' target='_blank'>“El expediente”</a>, publicado en Youtube el 20 de junio del 2015 por la cadena CN5 de Argentina, se dedica al esclarecimiento del “misterio de la corbata colombiana”. El “misterio” se refiere a la aparición de un cuerpo desnudo en extrañas circunstancias en una vía que conecta a la capital argentina con Mar del Plata. El cuerpo presentaba “un golpe en la cabeza, traumatismo de cráneo, y un profundo golpe en la región del cuello, un corte muy particular (…)”. El nombre del capítulo, aclara el presentador, se refiere al tipo de crimen: “corbata colombiana, es un crimen horroroso, pero de película de terror, que tiene que ver con los ajustes de cuentas entre mafias”. En el programa, cuando se da contexto al nombre del tipo de crimen, no se mencionan los cortes sobre el cuepo característicos de La violencia bipartidista. El locutor afirma que el objetivo de los crímenes de la mafia es el de enviar mensajes y en el caso específico de la “corbata” el mensaje tiene que ver con la retaliación a los que hablan de más: “producen un corte a la altura de la garganta, donde nace la lengua, por eso es la corbata colombiana, ¿por qué la lengua? Porque con la lengua se habla, le sacan literalmente la lengua por la garganta, y ese mensaje es: por buchón te pasa esto, por hablar te pasa esto”. Mientras van hablando muestran una imagen pixelada de la víctima, y aclaran “obviamente tapamos, obviamente no mostramos”. Esa imagen la alternan con la de un tatuaje en la que se ve, de modo caricaturesco, “la corbata colombiana”, “ahí está ese tatuaje, ese tatuaje significa la corbata colombiana, lo mostramos para no mostrar directamente”.</p>
    <p>¿Cómo llegó el “corte de corbata”, este corte de La violencia de los años 50, a ser conocido internacionalmente como “la corbata colombiana”, o, en inglés: “colombian necktie”?. Una simple búsqueda en google usando estos dos últimos términos nos arroja una gran cantidad de resultados en los que pueden encontrarse referencias culturales, noticias de hechos de violencia, tatuajes, disfraces de Halloween, escenificaciones hechas con maquillaje, etc. Se hace referencia a la “corbata” en múltiples productos de la cultura popular como canciones, series de televisión y películas, e incluso tiene una página de <a href='https://en.wikipedia.org/wiki/Colombian_necktie' target='_blank'>Wikipedia</a>.</p>
    <img src='assets/imgs/montaje/otras/14.jpg' alt='La corbata colombiana'/>
    <p>La reproducción extendida de este ícono en múltiples imágenes y sus referencias en los productos de la cultura popular son una oportunidad para volver sobre los reclamos, hechos tanto en el contexto popular, como en el de la academia, al respecto de la utilización de imágenes para la representación de hechos violentos: se afirma que son insuficientes para dar cuenta de acontecimientos que son en esencia irrepresentables, que su alta circulación tiene una suerte de efecto inmunizador que redunda en la tolerancia creciente hacia los estímulos provocados por ellas, que son simulacros que falsifican la complejidad de la realidad, que son mercancías cuya circulación coartan las recepciones reflexivas de los espectadores o que son ídolos cuyos análisis propician apologías del horror.</p>
    <p>De este modo, el presente montaje asume la posición de que estos reclamos no pueden ser excusa para dejar de hacer sentido con eeste tipo de imágenes. Y que es necesaria la producción de herramientas críticas que permitan el acercamiento reflexivo para entender lo que su proliferación en diferentes contextos tiene para decir. En este sentido, lo que se pretende es poner estas imágenes en contexto, propiciar la distancia crítica y el establecimiento de conclusiones que no se restrinjan al horror o a la indiferencia. El procedimiento es del montaje y está inspirado en posturas formuladas por Walter Benjamin en su Libro de los pasajes (2005), y por Aby Warburg en su Atlas Mnemosyne (2010) </p>
    <div class="img-montaje"><img src='assets/imgs/montaje/otras/17.jpg' alt='el libro de los pasajes'/><img src='assets/imgs/montaje/otras/16.jpg' alt='Mnemosyne'/></div>
    <p>El montaje entonces abarca un gran número de prácticas espectaculares, plásticas y literarias y representa una actitud determinada hacia la relación entre la parte y el todo que todavía está por determinar de manera íntegra. Desde este punto de vista del montaje, no es posible hablar de “la” imagen, sino de imágenes múltiples, parciales, desiguales y fragmentarias; imágenes que adecuadamente dispuestas pueden ocasionar choques dinámicos que dan lugar a relámpagos fugaces de inteligibilidad. Más allá de los alegatos que reducen a las imágenes a mercancías, simulacros o ídolos, el procedimiento del montaje establece relaciones teniendo en cuenta la estructura frágil y difícil de las imágenes, mientras trata de buscar sentidos con base en el establecimiento de variados tipos de correspondencias visuales, a partir de las cuales es posible pensar al mismo tiempo diferentes épocas históricas y diferentes contextos de producción y de recepción.</p>
    <img src="https://terceraorbita.com/wp-content/uploads/2022/11/VERTOV.png" alt="Vertov">
    <p>Hay dos características básicas que se destacan en la presentación de este procedimiento. En primer lugar, la importancia con la que son tratados −desde un punto de vista epistemológico− los fenómenos particulares, los cuales no son agrupados bajo operaciones inductivas ni deductivas sino más bien de naturaleza “ejemplar” o “paradigmática”. De este modo, al tratar cada imagen como un singular, el montaje puede hacer visibles las diferencias de sentido que van de una imagen a otra y ponerlas en tensión. En segundo lugar, el hecho de que permite encontrar semejanzas en estas diferencias para establecer correspondencias entre los diferentes contextos históricos y geográficos en los que las imágenes han sido producidas. Así, el montaje posibilita una presentación de la historia que muestre las semejanzas y diferencias entre ciertas prácticas y acontecimientos de distintas épocas, e impugne las presentaciones prefiguradas de la sucesión de los hechos históricos, de acuerdo con las cuales la historia se dirige de modo inexorable al mejor de los mundos posibles o a una inevitable catástrofe. Es decir, los problemas acerca de cómo poner en relación los diferentes elementos del archivo implican, a la vez, una específica concepción de la temporalidad que trata de definirse por oposición al modo lineal y prefigurado de entender el tiempo histórico.</p>
    <p><img class='panel'src='https://www.engramma.it/eOS/resources/images/1046/T46_800.jpg' alt='Panel 46 del Atlas Mnemosyne'></p><h5>Atlas Mnemosyne. <a href='https://www.engramma.it/eOS/core/frontend/eos_atlas_index.php?id_tavola=1046' target='_blank'>Panel 46</a>: Ninfa. 'Date prisa, tráelo' en el círculo Tornabuoni. Domesticación</h5>
    <h2>Sobre las imágenes de la violencia en Colombia</h2>
    <p>Existe un abundante archivo de imágenes acerca de la violencia en Colombia, que puede ser organizado de diferentes maneras atendiendo a sus relaciones temáticas, morfológicas y gestuales. Dentro de todas esas posibilidades de organización se puede mencionar una iconografía bastante patética, que da cuenta de las diferentes técnicas de desmembramiento y mutilación, en las cuales el cuerpo humano es sometido a una serie de transformaciones que se efectúan con instrumentos cortantes como cuchillos, puñales y machetes. Esos cortes fueron practicados principalmente en la época de la violencia bipartidista. Sin embargo, diferentes estudios muestran que ya desde el siglo XIX se llevaban a cabo prácticas similares y que persisten aún en la actualidad en los procedimientos de los diferentes actores del conflicto</p>
    <div class="img-montaje"><img src='https://www.banrepcultural.org/historia-natural-politica/images/flora/quijano01.jpg' alt='Quijano'/><img src='https://estonoescritica.files.wordpress.com/2020/07/el-martirio-agiganta-a-los-hombres-rac3adz.1966.png?w=875' alt='Alccantara'/></div>
    <p>Lo que hace interesante el acercamiento a esta iconografía es que pareciera que hubiera perdido su actualidad. Incluso en los campos de la historia y crítica de arte, las imágenes más explícitas y viscerales sobre los cuerpos rotos son consideradas como anacrónicas, como el testimonio de momentos en que el arte estaba dedicado a desfiguraciones expresionistas o a estrategias de choque directo con pretensiones políticas (Roca, 2001). Esas imágenes son recurrentemente tildadas de sensacionalistas (Reyes, 1999) , y se afirma que su crudeza ha perdido, “a fuerza de ser vistas, su capacidad de conmover” (Roca, 2001, p. 60). De esta manera, este tipo de tendencias de crítica de arte, entierran en un pasado anacrónico las imágenes explícitas, mientras valoran de manera positiva el hecho de que, por el contrario, los artistas desde la década de los noventas hasta el presente, buscan aludir de modo indirecto, a través de diferentes tipos de asociaciones complejas, y en consonancia con las tendencias conceptuales del arte contemporáneo, a la violencia que se ha perpetrado sobre los cuerpos de los colombianos.</p>
    <div class="img-montaje"><img src='https://jmechavarria.com/wp-content/uploads/2019/04/corte_1_Orquis-Lugubris_v2-1.png' alt='Echevaria'/><img src='https://www.banrepcultural.org/historia-natural-politica/images/flora/Cardoso01.jpg' alt='Corona'/></div>
    <p>Sin embargo, esas imágenes no han perdido necesariamente su vigencia, siguen circulando, reactivando y actualizando sus significaciones, apareciendo aquí y allá en todo tipo de contextos. La hipótesis que se sostiene acá, es que esto tiene que ver con que las prácticas que han dado origen a esas imágenes, el pathos que estas han cristalizado, no ha cesado; sigue manifestándose y haciendo parte de la cotidianidad de una sociedad en la que supuestamente deben ser catalogadas de excepcionales y anacrónicas. Por esta razón, la iconografía del cuerpo roto puede posibilitar una entrada crítica al asunto de la relación que hay entre el retorno o la supervivencia de ciertos motivos iconográficos y las prácticas violentas a las que estas se refieren. La pregunta sobre las condiciones de posibilidad de esas imágenes es una pregunta sobre la historia misma; sobre los contextos históricos en que han sido posibles. No pueden ser consideradas simplemente como meros simulacros, fenómenos mediáticos, sensacionalistas o espectaculares. El hecho de que sean recurrentes y supervivan, autoriza a abrir la pregunta sobre el modo ambivalente de experimentar el tiempo, que se debate entre el eterno retorno de la violencia y el progreso de una sociedad en las que esta no tiene cabida</p>
    <h2>Variaciones en torno al Corte de corbata.</h2>
    <p>El corte de corbata es una práctica violenta sobre la corporalidad que “se verifica mediante una incisión por debajo del maxilar inferior por donde se hace pasar la lengua de la víctima quedando izada en forma espeluznante sobre el cuello” (Guzmán, Fals Borda & Umaña, 2005, p. 248) . Esta práctica se ha convertido en una suerte de emblema de la violencia de los años 50’s, y en general de la violencia en Colombia . Hay interesantes variaciones de este motivo iconográfico en distintos contextos de circulación de imágenes. El ícono, que en principio se refería a una práctica concreta en un horizonte temporal específico, se ha desplazado para reconfigurarse en distintos contextos en los que cada manifestación da cuenta de un modo singular y diferente del problema de las relaciones entre violencia y silencio, tema particularmente propicio para una reflexión sobre los límites de la representación de la violencia. </p>
    <div class="img-montaje"><img src='assets/imgs/8.jpg' alt="Caudillo con lengua"><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/05orpheu.jpg/800px-05orpheu.jpg' alt='La muerte de Orfeo'/></div>
    <p>El motivo iconográfico de la lengua cercenada o reconfigurada puede ser considerado una pathosformel que pone en escena relaciones patéticas entre la violencia y el silencio. Las prácticas violentas sobre la corporalidad han sido descritas por Uribe (2004) y Blair (2005) como escenificaciones rituales del exceso. Ambas autoras han recurrido al teatro para elaborar una categoría: “teatralidades del exceso” con la cual abordan la puesta en escena que está implícita en estas prácticas. Las manifestaciones visuales de prácticas como el corte de corbata, ponen ante los ojos de los espectadores y de los artistas un tremendo pathos violento que exige de ellos algún tipo de respuesta emotiva y contemplativa, que puede abarcar diferentes manifestaciones y gradaciones en el espectro de lo que Warburg llama “los dos polos fronterizos del comportamiento psíquico”, es decir, “la contemplación tranquila o la entrega orgiástica” (Warburg 2012, p. 29). El espectador ante una “escenificación” tal, puede oscilar entre la indiferencia, las respuestas emotivas inmediatas o las contemplaciones críticas y reflexivas. Estas últimas son las que necesitan el establecimiento de una “distancia para el pensamiento” (Denkraum) que posibilite dar un lugar estas manifestaciones en la historia de los hechos oprobiosos que han padecido los colombianos.</p>
    <p>Las imágenes de la lengua cercenada o reconfigurada tienen el potencial de hacer visible, de poner en escena, el pathos de la relación que la violencia tiene con el lenguaje, con la posibilidad de decirla o representarla. El pathos puede ser entendido como un padecer, como la acción externa que el cuerpo sufre y que no puede controlar, y que en este caso está relacionado con el lenguaje. Las imágenes que se refieren a esta práctica muestran la corporalidad expuesta a sufrir acciones violentas que transfiguran el órgano que mediante un procedimiento metonímico puede ser asociado al acto de habla y a su poder tanto crítico y/o destructivo como socializante y/o creativo . En estas imágenes la lengua se expone como una naturaleza muerta o petrificada, que al igual que la alegoría de la calavera del barroco (vanitas) da cuenta de la transitoriedad y corruptibilidad de lo orgánico, pero a diferencia de esta, no lo hace sólo por efecto del mero paso del tiempo sino por la transfiguración que una acción violenta efectiva puede ejercer sobre la corporalidad de un hablante.</p>
    <p>El siguiente montaje digital se creó a partir de una versión previamente publicada en formato físico (Urueña, 2017). Se utilizó el lenguaje de las Humanidades digitales para reconceptualizar el ejercicio como una visualización de datos humanísticos. Para ello, se desarrolló una pequeña base de datos con las imágenes del montaje y se construyó una narración interactiva que permite explorar las imágenes haciendo clic en sus áreas correspondientes. Esta visualización se realizó mediante la librería de narraciones interactivas Aventura.js, adaptada en esta ocasión para crear una narración iconográfica que captura la forma compositiva del montaje y las variaciones visuales del Corte de Corbata.</p>
    <div class="panel"><PanelLengua/></div>
    <iframe width="100%" frameborder="0" src="https://observablehq.com/embed/330f841b0474e672?cells=tabla" title="Tabla de imágenes"></iframe>
    <p>A través de las imágenes de la lengua cercenada o reconfigurada, es posible establecer relaciones alegóricas entre la violencia y el lenguaje, o entre la violencia y el silencio. En el sentido de cómo aquella puede callar por la fuerza desde un punto de vista fisiológico, al cesar la existencia orgánica del hablante. También en el sentido en que Benjamin relaciona la muerte con el significado: el lenguaje entendido como vehículo de significantes que proliferan desmedidamente y que por esa razón se vuelven vacíos (2006 [1927], p. 383) . Así, puede pensarse la influencia simbólica que la violencia ejerce sobre el lenguaje, y que las condiciones de una época de crisis exacerban. La lengua transfigurada pone en escena la (im)posibilidad de “decir verdad” en el contexto de unas políticas de la memoria que la demandan; esto es, de la circunstancia de que sobre los hablantes penda como una “amenaza” (Benjamin, 2007b, p. 191) terriblemente ambigua la posibilidad de que su lenguaje sea mortificado, tanto por las limitaciones fisiológicas a las que es sometido cuando la violencia efectiva y concreta atenta contra la corporalidad, como por las propias limitaciones epistemológicas a las que puede ser sometido en contextos sociales en los que la articulación de sentido, e incluso la posibilidad de la enunciación misma, se hace difícil.</p>
    <img src="assets/imgs/montaje/otras/18.jpg" alt="Lengua de San Juan Nepomuceno"/>
    <p>A partir de las imágenes mencionadas es posible ver la supervivencia del pathos del silencio provocado por la violencia sobre el discurso en diferentes manifestaciones visuales. Un ícono que se usa tanto para emblematizar por medio de lenguajes artísticos los problemas del conflicto en Colombia, como para dar cuenta de la banalización, caricaturización y despolarización, de que pueden adolecer las imágenes de la violencia dadas las actuales condiciones de circulación. A través de las diferentes manifestaciones de la lengua cercenada o reconfigurada, esta supervivencia no da cuenta de un arquetipo a-histórico o a-temporal invariable, sino que está situada históricamente mediante las variaciones concretas que se manifiestan en el soporte sensible que proporciona la imagen y cuyo sentido puede cambiar dependiendo de los contextos de circulación. </p>
    <p>Esas manifestaciones bien podrían mostrarse como hechos excepcionales en el contexto de una organización política en la que no tienen cabida y no pueden ser pensadas. Sin embargo, pueden ayudar a reflexionar acerca de una organización de la experiencia temporal diferente a la signada por la imagen del progreso. La relación entre las formas jurídicas de organización modernas y las prácticas míticas de la violencia no puede ser formulada en modo de relaciones de sucesión progresiva, sino que deben ser entendidas como coexistentes. La violencia sigue manifestándose de modo sincrónico a la organización de formas jurídicas que se supone la han desterrado. La temporalidad histórica se experimenta así de modo esquizoide: las personas sienten que no se logra el progreso porque no se han eliminado las lacras que no dejan realizar la promesa a plenitud, pero a la vez, están convencidas de que se encuentran en un momento histórico privilegiado en relación con las épocas anteriores. Se siente a la vez el progreso y el retorno persistente de las condiciones que no dejan realizarlo.</p>
    <p>En lo que tiene que ver con la relación entre lenguaje y violencia, este modo de poner las cosas es especialmente interesante, porque las sociedades democráticas contemporáneas y los discursos que las legitiman, plantean recurrentemente la importancia del uso de la palabra en forma de deliberación y de participación, como un requisito sin el cual no es posible su realización plena. La reflexión que posibilita la persistencia del motivo de la lengua violentada –tanto desde el punto de vista simbólico como el fisiológico– puede mostrar el problema de la realización del proyecto democrático y de las tesis que lo postulan como el mejor sistema de organización social posible. Esa realización no será posible mientras no se tomen en cuenta, hasta un punto límite, las posibilidades mismas del lenguaje para contener la violencia efectiva que es causada sobre los hablantes, y para repensar las razones que explican el hecho de que la sociedad que la ejerce sea la misma que pretende haberla superado.</p>
</div>

<style>

    .container {
            
            font-family: 'Public Sans', sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto; /* Centrar horizontalmente el contenido */
            padding: 80px;
            background-color: #faf8ff;
            border: solid 1px #363636;
            text-align: justify;
            color: #363636;
        }

        .container img {
            width: 100%;
        }
    
        h1 {
            margin-bottom: 10px;
            font-size: 3vw;
            font-weight: 400;
            color: #8685ef;
        }
    
        p {
            font-size: 16px;
            margin-bottom: 10px;
        }

    
        a {
            color: #8685ef;
            text-decoration: none;
        }
    
        a:hover {
            text-decoration: underline;
        }
    
        .img-montaje {
            display: flex;
            flex-direction: row;
            width: 100%;
            justify-content: space-between;
        }
    @media (max-width: 768px) {

    
    .container {
      max-width: 100%;
      padding: 3vw;
    }
      }
    
    </style>
    